//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    using UnityEngine.SceneManagement;
    
    
    public class Win : TypedScene
    {
        
        private const string GUID = "a54dfb119218ff14f9f73a3101c8b6c1";
        
        public static void Load(GameManager.GameResult argument, LoadSceneMode loadSceneMode = LoadSceneMode.Single)
        {
            LoadScene(GUID, loadSceneMode, argument);
        }
    }
}
